import{NextResponse}from"next/server";import{createClient}from"@supabase/supabase-js";
const db=()=>createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!);
const questions=[["gender","برای چه کسی عطر می‌خواهید؟ مردانه، زنانه یا یونی‌سکس؟"],["family","چه حال‌وهوایی دوست دارید؟ چوبی، خنک، شیرین، شرقی، دریایی، مرکباتی یا ترکیبی؟"],["occasion","بیشتر برای چه موقعیتی می‌خواهید؟ روزمره، رسمی، مهمانی، قرار یا استفاده خاص؟"],["time","بیشتر روز استفاده می‌کنید یا شب؟"],["season","برای کدام فصل یا آب‌وهوا می‌خواهید؟"],["intensity","پخش بو را چطور می‌پسندید؟ ملایم، متوسط یا قوی؟"],["longevity","ماندگاری برایتان چقدر مهم است؟ متوسط یا خیلی زیاد؟"],["notes","اگر نت یا عطری دارید که دوست دارید، نامش را بگویید."],["first_name","نام کوچک شما چیست؟"],["last_name","نام خانوادگی شما چیست؟"],["phone","شماره تماس شما چیست؟"],["notes2","اگر توضیح یا درخواست دیگری دارید، همین‌جا بنویسید."]]; 
function nextIndex(p:any){return questions.findIndex(([k])=>!String(p?.[k]??"").trim())}
export async function POST(r:Request){try{const b=await r.json();const message=String(b.message||"").trim();if(!message)return NextResponse.json({error:"پیام خالی است."},{status:400});const s=db();let id=String(b.order_id||"");let prefs:any={};if(id){const old=await s.from("special_orders").select("*").eq("id",id).maybeSingle();if(old.data){prefs=old.data.preferences||{}}}
if(!id){const ins=await s.from("special_orders").insert({preferences:{}}).select("id").single();if(ins.error)throw ins.error;id=ins.data.id}
await s.from("special_order_messages").insert({special_order_id:id,role:"user",content:message});
const idx=nextIndex(prefs);if(idx>=0){const [key]=questions[idx];prefs[key]=message}
const next=nextIndex(prefs);let reply="";if(next<0){const fullName=(prefs.first_name+" "+prefs.last_name).trim();const up=await s.from("special_orders").update({first_name:prefs.first_name,last_name:prefs.last_name,phone:prefs.phone,preferences:prefs,notes:prefs.notes2||prefs.notes||null,status:"pending"}).eq("id",id);if(up.error)throw up.error;reply="ممنون. اطلاعات عطر ویژه شما ثبت شد. تیم عطر کهکشان درخواست را بررسی می‌کند و برای قیمت، امکان ساخت و موجودی با شما تماس می‌گیرد."}else{reply=idx===0?"به بخش «عطر ویژه» خوش آمدید. من برای پیدا کردن یا طراحی رایحه مناسب همراه شما هستم. "+questions[next][1]:questions[next][1]}
await s.from("special_order_messages").insert({special_order_id:id,role:"assistant",content:reply});return NextResponse.json({order_id:id,reply,done:next<0})}catch(e){return NextResponse.json({error:"ثبت درخواست عطر ویژه انجام نشد."},{status:500})}}