import {NextResponse} from "next/server";
import {createClient} from "@supabase/supabase-js";
const db=()=>createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!);
type Prefs={product_type?:string;gender?:string;target?:string;occasion?:string;gift_occasion?:string;time?:string;season?:string;longevity?:string;sillage?:string;scent?:string[];birth_month?:string;budget?:number|null};
const months=["فروردین","اردیبهشت","خرداد","تیر","مرداد","شهریور","مهر","آبان","آذر","دی","بهمن","اسفند"];
const scentMap:[string,string[]][]=[["شیرین",["شیرین","وانیلی","کاراملی","میوه‌ای"]],["تند",["تند","ادویه‌ای","فلفلی"]],["خنک",["خنک","تازه","fresh"]],["ملایم",["ملایم","نرم","لطیف"]],["گرم",["گرم","عنبر","کهربا"]],["تلخ",["تلخ","bitter"]],["چوبی",["چوبی","wood","عود"]],["مرکباتی",["مرکبات","مرکباتی","citrus"]],["دریایی",["دریایی","آبی","aquatic","marine"]],["شرقی",["شرقی","oriental"]],["گلدار",["گل","گلدار","رز","یاس"]],["پودری",["پودری","پودر"]]];
const normalize=(s:string)=>s.toLowerCase().replace(/[يى]/g,"ی").replace(/[ك]/g,"ک").replace(/[ۀة]/g,"ه").replace(/[\u200c\u200f]/g," ").replace(/[،؛]/g,",").trim();
const has=(s:string,words:string[])=>words.some(w=>normalize(s).includes(normalize(w)));
function extract(message:string,p:Prefs){const n=normalize(message);const out:{key:keyof Prefs;value:any}[]=[];
if(has(n,["ادکلن","کولون","cologne"]))out.push({key:"product_type",value:"ادکلن"});else if(has(n,["عطر","پرفیوم","perfume"]))out.push({key:"product_type",value:"عطر"});
if(has(n,["مرد","مردانه","پسر","آقا","male"]))out.push({key:"gender",value:"مردانه"});else if(has(n,["زن","زنانه","دختر","خانم","female"]))out.push({key:"gender",value:"زنانه"});else if(has(n,["یونی","یونیسکس","unisex","هر دو"]))out.push({key:"gender",value:"یونی‌سکس"});
if(has(n,["خودم","برای خود","برای من"]))out.push({key:"target",value:"خودم"});else if(has(n,["هدیه","کادو","برای همسر","برای مادر","برای پدر","برای دوست","برای دیگری"]))out.push({key:"target",value:"هدیه/شخص دیگر"});
for(const x of ["تولد","سالگرد","عروسی","روز مادر","روز پدر","ولنتاین","مهمانی","قرار","رسمی","روزمره","دانشگاه","محل کار"])if(n.includes(x)){out.push({key:(p.target==="هدیه/شخص دیگر"||has(n,["هدیه","کادو"]))?"gift_occasion":"occasion",value:x});break}
if(has(n,["صبح","ظهر","روز"]))out.push({key:"time",value:"روز"});else if(has(n,["شب","شبانه"]))out.push({key:"time",value:"شب"});
for(const x of ["بهار","تابستان","پاییز","زمستان"])if(n.includes(x)){out.push({key:"season",value:x});break}
const longevityText=n.includes("ماندگاری")?n:"";if(has(longevityText,["خیلی زیاد","خیلی بالا","بسیار زیاد"]))out.push({key:"longevity",value:"خیلی زیاد"});else if(has(longevityText,["زیاد","بالا","ماندگار"]))out.push({key:"longevity",value:"زیاد"});else if(has(longevityText,["متوسط"]))out.push({key:"longevity",value:"متوسط"});else if(has(longevityText,["کم"]))out.push({key:"longevity",value:"کم"});
const sillageText=n.includes("پخش بو")?n:"";if(has(sillageText,["خیلی قوی","پخش بالا","بمب"]))out.push({key:"sillage",value:"خیلی قوی"});else if(has(sillageText,["قوی","زیاد"]))out.push({key:"sillage",value:"قوی"});else if(has(sillageText,["متوسط"]))out.push({key:"sillage",value:"متوسط"});else if(has(sillageText,["ملایم","کم"]))out.push({key:"sillage",value:"ملایم"});
const scents=scentMap.filter(([,words])=>has(n,words)).map(([name])=>name);if(scents.length)out.push({key:"scent",value:Array.from(new Set([...(p.scent||[]),...scents]))});
for(const m of months)if(n.includes(m)){out.push({key:"birth_month",value:m});break}
if(has(n,["فرقی ندارد","مهم نیست","ندارم","بدون محدودیت"]))out.push({key:"budget",value:null});else{const nums=message.replace(/[۰-۹]/g,d=>String("۰۱۲۳۴۵۶۷۸۹".indexOf(d))).match(/\d{4,}/g);if(nums?.length)out.push({key:"budget",value:Number(nums[nums.length-1])})}
return out}
const order=["product_type","gender","target","occasion","gift_occasion","time","season","longevity","sillage","scent","birth_month","budget"] as (keyof Prefs)[];
const questions:Record<string,string>={product_type:"اول مشخص کنیم: عطر می‌خواهید یا ادکلن؟",gender:"برای چه جنسیتی می‌خواهید؟ مردانه، زنانه یا یونی‌سکس؟",target:"برای خودتان می‌خواهید یا برای شخص دیگری/هدیه؟",occasion:"برای چه مناسبتی می‌خواهید؟ مثلاً روزمره، رسمی، مهمانی یا قرار.",gift_occasion:"اگر هدیه است، مناسبت هدیه چیست؟ مثلاً تولد، سالگرد یا ولنتاین.",time:"بیشتر برای روز می‌خواهید یا شب؟",season:"برای کدام فصل یا آب‌وهوا می‌خواهید؟",longevity:"ماندگاری را چطور می‌پسندید؟ کم، متوسط، زیاد یا خیلی زیاد؟",sillage:"پخش بو را چطور می‌پسندید؟ ملایم، متوسط، قوی یا خیلی قوی؟",scent:"چه رایحه‌ای دوست دارید؟ شیرین، تند، خنک، ملایم، گرم، تلخ، چوبی، مرکباتی، دریایی، شرقی، گلدار یا پودری.",birth_month:"ماه تولد شما یا شخصی که برای او می‌خواهید چیست؟",budget:"بودجه حدودی دارید؟ اگر محدودیتی ندارید فقط بگویید «فرقی ندارد»."};
const nextKey=(p:Prefs)=>order.find(k=>(k!=="gift_occasion"||p.target==="هدیه/شخص دیگر")&&(p[k]===undefined||p[k]===""))||null;
const intent=(m:string)=>{const n=normalize(m);if(has(n,["آدرس","نشانی","کجا هستید"]))return"address";if(has(n,["اینستا","اینستاگرام","تلگرام","واتساپ","روبیکا","آپارات"]))return"social";if(has(n,["شماره تماس","پشتیبانی","تماس"]))return"support";if(has(n,["سلام","درود"]))return"greeting";return"other"};
async function info(s:any){const {data}=await s.from("store_settings").select("address,support_phone,social_links").limit(1).maybeSingle();return data||{}}
function recommend(products:any[],p:Prefs){return products.filter(x=>Number(x.stock)>0).map(x=>{const text=normalize([x.name,x.description,...Object.values(x.fragrance_profile||{})].filter(Boolean).join(" "));let score=0;if(p.product_type&&text.includes(normalize(p.product_type)))score+=12;if(p.gender&&text.includes(normalize(p.gender)))score+=12;for(const z of p.scent||[])if(text.includes(normalize(z)))score+=12;if(p.season&&text.includes(normalize(p.season)))score+=6;if(p.occasion&&text.includes(normalize(p.occasion)))score+=6;if(p.longevity&&text.includes(normalize(p.longevity)))score+=5;if(p.sillage&&text.includes(normalize(p.sillage)))score+=5;if(typeof p.budget==="number"&&Number(x.price)<=p.budget)score+=5;return {...x,score}}).sort((a,b)=>b.score-a.score).slice(0,3)}
const money=(n:number)=>new Intl.NumberFormat("fa-IR").format(Math.round(n))+" تومان";
export async function POST(request:Request){try{const b=await request.json();const message=String(b.message||"").trim();if(!message)return NextResponse.json({error:"پیام خالی است."},{status:400});const s=db();let id=String(b.order_id||"");let prefs:Prefs={};if(id&&!b.reset){const old=await s.from("special_orders").select("id,preferences").eq("id",id).maybeSingle();if(old.data)prefs=(old.data.preferences||{}) as Prefs}if(!id||b.reset){const ins=await s.from("special_orders").insert({visitor_id:String(b.visitor_id||"").slice(0,80),preferences:{},status:"draft"}).select("id").single();if(ins.error)throw ins.error;id=ins.data.id;prefs={}}await s.from("special_order_messages").insert({special_order_id:id,role:"user",content:message});
const it=intent(message);if(it==="address"||it==="social"||it==="support"){const x=await info(s);let reply="";if(it==="address")reply=x.address?"آدرس عطر کهکشان: "+x.address:"آدرس هنوز ثبت نشده است.";if(it==="support")reply=x.support_phone?"شماره پشتیبانی: "+x.support_phone:"شماره پشتیبانی هنوز ثبت نشده است.";if(it==="social")reply=Array.isArray(x.social_links)&&x.social_links.length?x.social_links.map((z:any)=>z?.name&&z?.url?z.name+": "+z.url:"").filter(Boolean).join("\n"):"پیج‌ها هنوز ثبت نشده‌اند.";await s.from("special_order_messages").insert({special_order_id:id,role:"assistant",content:reply});return NextResponse.json({order_id:id,reply,done:false,intent:it,preferences:prefs})}
const current=nextKey(prefs);const extracted=extract(message,prefs);if(current&&it!=="greeting"&&!extracted.some(x=>x.key===current)){for(const x of extracted){if(x.key==="scent")prefs.scent=x.value;else prefs[x.key]=x.value}const reply="پاسخ شما با سؤال فعلی هماهنگ نیست. اطلاعات دیگری که گفتید را نگه داشتم، اما ابتدا باید به این سؤال پاسخ بدهید:\n\n"+questions[current];await s.from("special_order_messages").insert({special_order_id:id,role:"assistant",content:reply});return NextResponse.json({order_id:id,reply,done:false,intent:"invalid",preferences:prefs})}
for(const x of extracted){if(x.key==="scent")prefs.scent=x.value;else prefs[x.key]=x.value}
if(it==="greeting"&&Object.keys(prefs).length===0){const reply="به عطر کهکشان خوش آمدید ✦ من سلیقه شما را تحلیل می‌کنم و در پایان از موجودی واقعی فروشگاه چند انتخاب دقیق پیشنهاد می‌دهم.\n\n"+questions[nextKey(prefs)!];await s.from("special_order_messages").insert({special_order_id:id,role:"assistant",content:reply});return NextResponse.json({order_id:id,reply,done:false,intent:"greeting",preferences:prefs})}
const next=nextKey(prefs);if(next){const reply=questions[next];await s.from("special_order_messages").insert({special_order_id:id,role:"assistant",content:reply});return NextResponse.json({order_id:id,reply,done:false,intent:it,preferences:prefs})}
const {data:products}=await s.from("products").select("id,name,description,price,stock,image_url,fragrance_profile").gt("stock",0).limit(100);const picks=recommend(products||[],prefs);const pickText=picks.length?picks.map((x:any,i:number)=>(i+1)+". "+x.name+" | "+money(x.price)+" | تناسب تقریبی "+Math.min(99,70+x.score)+"٪").join("\n"):"در حال حاضر محصول کاملاً منطبق و موجود پیدا نشد.";await s.from("special_orders").update({preferences:prefs,status:"pending",notes:"پروفایل تشخیص عطر تکمیل شد."}).eq("id",id);const reason=[prefs.product_type,prefs.gender,(prefs.scent||[]).join("، "),prefs.season,prefs.occasion].filter(Boolean).join("، ");const reply="پروفایل رایحه شما کامل شد. ✦\n\nانتخاب‌های پیشنهادی:\n"+pickText+"\n\nدلیل انتخاب: "+reason+"\n\nاگر نام یک عطر، برند، رایحه یا قیمت مشخص دارید، آن را بگویید تا انتخاب را دقیق‌تر کنم.";await s.from("special_order_messages").insert({special_order_id:id,role:"assistant",content:reply});return NextResponse.json({order_id:id,reply,done:true,intent:"recommendation",preferences:prefs,recommendations:picks.map((x:any)=>({id:x.id,name:x.name,price:x.price,image_url:x.image_url,score:x.score}))})}catch{return NextResponse.json({error:"در پردازش درخواست عطر مشکلی پیش آمد. لطفاً دوباره تلاش کنید."},{status:500})}}
