import {NextResponse} from "next/server";
import {createClient} from "@supabase/supabase-js";
const db=()=>createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!);
type Prefs={product_type?:string;gender?:string;target?:string;occasion?:string;gift_occasion?:string;time?:string;season?:string;longevity?:string;sillage?:string;scent?:string[];birth_month?:string;budget?:number|null;first_name?:string;last_name?:string;phone?:string};
const months=["فروردین","اردیبهشت","خرداد","تیر","مرداد","شهریور","مهر","آبان","آذر","دی","بهمن","اسفند"];
const scentMap:[string,string[]][]=[["شیرین",["شیرین","وانیلی","کاراملی","میوه‌ای"]],["تند",["تند","ادویه‌ای","فلفلی"]],["خنک",["خنک","تازه","fresh"]],["ملایم",["ملایم","نرم","لطیف"]],["گرم",["گرم","عنبر","کهربا"]],["تلخ",["تلخ","bitter"]],["چوبی",["چوبی","wood","عود"]],["مرکباتی",["مرکبات","مرکباتی","citrus"]],["دریایی",["دریایی","آبی","aquatic","marine"]],["شرقی",["شرقی","oriental"]],["گلدار",["گل","گلدار","رز","یاس"]],["پودری",["پودری","پودر"]]];
const normalize=(s:string)=>s.toLowerCase().replace(/[يى]/g,"ی").replace(/[ك]/g,"ک").replace(/[ۀة]/g,"ه").replace(/[\u200c\u200f]/g," ").replace(/[،؛]/g,",").replace(/[۰-۹]/g,d=>String("۰۱۲۳۴۵۶۷۸۹".indexOf(d))).replace(/[؟?!]+/g," ").replace(/\s+/g," ").trim();
const has=(s:string,words:string[])=>words.some(w=>normalize(s).includes(normalize(w))); const anyExact=(s:string,words:string[])=>words.some(w=>normalize(s)===normalize(w));
function extract(message:string,p:Prefs,current?:keyof Prefs){const n=normalize(message);const out:{key:keyof Prefs;value:any}[]=[];
if(has(n,["ادکلن","کولون","cologne"]))out.push({key:"product_type",value:"ادکلن"});else if(has(n,["عطر","پرفیوم","perfume"]))out.push({key:"product_type",value:"عطر"});
if(has(n,["مرد","مردانه","پسر","آقا","male"]))out.push({key:"gender",value:"مردانه"});else if(has(n,["زن","زنانه","دختر","خانم","female"]))out.push({key:"gender",value:"زنانه"});else if(has(n,["یونی","یونیسکس","unisex","هر دو"]))out.push({key:"gender",value:"یونی‌سکس"});
if(has(n,["خودم","برای خود","برای من","خودم میخوام","برای خودم"]))out.push({key:"target",value:"خودم"});else if(has(n,["هدیه","کادو","همسرم","همسر","دوستم","دوست من","مادرم","پدرم","خواهرم","برادرم","برای همسر","برای مادر","برای پدر","برای دوست","برای دیگری","برای شخص دیگر"]))out.push({key:"target",value:"هدیه/شخص دیگر"});
for(const x of ["تولد","سالگرد","عروسی","روز مادر","روز پدر","ولنتاین","مهمانی","قرار","رسمی","روزمره","دانشگاه","محل کار"])if(n.includes(x)){out.push({key:(p.target==="هدیه/شخص دیگر"||has(n,["هدیه","کادو"]))?"gift_occasion":"occasion",value:x});break}
if(has(n,["صبح","ظهر","روز"]))out.push({key:"time",value:"روز"});else if(has(n,["شب","شبانه"]))out.push({key:"time",value:"شب"});
for(const x of ["بهار","تابستان","پاییز","زمستان"])if(n.includes(x)){out.push({key:"season",value:x});break}
const longevityText=n.includes("ماندگاری")?n:"";if(has(longevityText,["خیلی زیاد","خیلی بالا","بسیار زیاد"]))out.push({key:"longevity",value:"خیلی زیاد"});else if(has(longevityText,["زیاد","بالا","ماندگار"]))out.push({key:"longevity",value:"زیاد"});else if(has(longevityText,["متوسط"]))out.push({key:"longevity",value:"متوسط"});else if(has(longevityText,["کم"]))out.push({key:"longevity",value:"کم"});if(current==="longevity"&&!out.some(x=>x.key==="longevity")){if(anyExact(n,["خیلی زیاد","خیلی بالا","بسیار زیاد"]))out.push({key:"longevity",value:"خیلی زیاد"});else if(anyExact(n,["زیاد","بالا","ماندگار"]))out.push({key:"longevity",value:"زیاد"});else if(anyExact(n,["متوسط"]))out.push({key:"longevity",value:"متوسط"});else if(anyExact(n,["کم","ضعیف"]))out.push({key:"longevity",value:"کم"});}
const sillageText=n.includes("پخش بو")||n.includes("خط بو")?n:"";if(has(sillageText,["خیلی قوی","پخش بالا","بمب"]))out.push({key:"sillage",value:"خیلی قوی"});else if(has(sillageText,["قوی","زیاد"]))out.push({key:"sillage",value:"قوی"});else if(has(sillageText,["متوسط"]))out.push({key:"sillage",value:"متوسط"});else if(has(sillageText,["ملایم","کم"]))out.push({key:"sillage",value:"ملایم"});
if(current==="sillage"&&!out.some(x=>x.key==="sillage")){if(has(n,["خیلی قوی","خیلی زیاد","بسیار قوی"]))out.push({key:"sillage",value:"خیلی قوی"});else if(anyExact(n,["قوی","زیاد","بالا"]))out.push({key:"sillage",value:"قوی"});else if(anyExact(n,["متوسط"]))out.push({key:"sillage",value:"متوسط"});else if(anyExact(n,["ملایم","کم","ضعیف"]))out.push({key:"sillage",value:"ملایم"});}
const scents=scentMap.filter(([,words])=>has(n,words)).map(([name])=>name);if(scents.length)out.push({key:"scent",value:Array.from(new Set([...(p.scent||[]),...scents]))});
for(const m of months)if(n.includes(m)){out.push({key:"birth_month",value:m});break}
if(has(n,["فرقی ندارد","مهم نیست","ندارم","بدون محدودیت"]))out.push({key:"budget",value:null});else{const nums=message.replace(/[۰-۹]/g,d=>String("۰۱۲۳۴۵۶۷۸۹".indexOf(d))).match(/\d{4,}/g);if(nums?.length)out.push({key:"budget",value:Number(nums[nums.length-1])})}
return out}
const order=["product_type","gender","target","occasion","gift_occasion","time","season","longevity","sillage","scent","birth_month","budget"] as (keyof Prefs)[];
const questions:Record<string,string>={product_type:"اول مشخص کنیم: عطر می‌خواهید یا ادکلن؟",gender:"برای چه جنسیتی می‌خواهید؟ مردانه، زنانه یا یونی‌سکس؟",target:"برای خودتان می‌خواهید یا برای شخص دیگری/هدیه؟",occasion:"برای چه مناسبتی می‌خواهید؟ مثلاً روزمره، رسمی، مهمانی یا قرار.",gift_occasion:"اگر هدیه است، مناسبت هدیه چیست؟ مثلاً تولد، سالگرد یا ولنتاین.",time:"بیشتر برای روز می‌خواهید یا شب؟",season:"برای کدام فصل یا آب‌وهوا می‌خواهید؟",longevity:"ماندگاری را چطور می‌پسندید؟ کم، متوسط، زیاد یا خیلی زیاد؟",sillage:"پخش بو را چطور می‌پسندید؟ ملایم، متوسط، قوی یا خیلی قوی؟",scent:"چه رایحه‌ای دوست دارید؟ شیرین، تند، خنک، ملایم، گرم، تلخ، چوبی، مرکباتی، دریایی، شرقی، گلدار یا پودری.",birth_month:"ماه تولد شما یا شخصی که برای او می‌خواهید چیست؟",budget:"بودجه حدودی دارید؟ اگر محدودیتی ندارید فقط بگویید «فرقی ندارد»."};
const nextKey=(p:Prefs)=>order.find(k=>(k!=="gift_occasion"||p.target==="هدیه/شخص دیگر")&&(p[k]===undefined||p[k]===""))||null;
const intent=(m:string)=>{const n=normalize(m);if(has(n,["آدرس","نشانی","کجا هستید","لوکیشن"]))return"address";if(has(n,["اینستا","اینستاگرام","پیج","تلگرام","واتساپ","روبیکا","آپارات"]))return"social";if(has(n,["شماره تماس","پشتیبانی","تماس"]))return"support";if(has(n,["محصولات","چه عطرهایی","چه ادکلن‌هایی","چی دارید","موجود دارید","قیمت"]))return"catalog";if(has(n,["سلام","درود"]))return"greeting";return"other"};
async function info(s:any){const {data}=await s.from("store_settings").select("address,support_phone,social_links").limit(1).maybeSingle();return data||{}}
function recommend(products:any[],p:Prefs){return products.filter(x=>Number(x.stock)>0).map(x=>{const text=normalize([x.name,x.description,...Object.values(x.fragrance_profile||{})].filter(Boolean).join(" "));let score=0;const add=(v:string|undefined,w:number)=>{if(v&&text.includes(normalize(v)))score+=w};add(p.product_type,10);add(p.gender,10);add(p.season,7);add(p.occasion,5);add(p.longevity,6);add(p.sillage,6);add(p.birth_month,4);for(const z of p.scent||[])add(z,12);if(typeof p.budget==="number"){const price=Number(x.price);if(price<=p.budget)score+=7;else if(price<=p.budget*1.1)score+=2;else score-=5}return {...x,score}}).sort((a,b)=>b.score-a.score).slice(0,3)}
const money=(n:number)=>new Intl.NumberFormat("fa-IR").format(Math.round(n))+" تومان";
const questionAccepts=(key:keyof Prefs,message:string)=>{
 const n=normalize(message);
 if(key==="product_type")return has(n,["عطر","پرفیوم","perfume","ادکلن","کولون","cologne"]);
 if(key==="gender")return has(n,["مرد","مردانه","پسر","آقا","زن","زنانه","دختر","خانم","یونی","یونیسکس","unisex"]);
 if(key==="target")return has(n,["خودم","برای خود","برای من","هدیه","کادو","همسر","دوست","مادر","پدر","خواهر","برادر","دیگری","شخص دیگر"]);
 if(key==="occasion")return has(n,["تولد","سالگرد","عروسی","ولنتاین","مهمانی","قرار","رسمی","روزمره","دانشگاه","محل کار","روز"]);
 if(key==="gift_occasion")return has(n,["تولد","سالگرد","عروسی","ولنتاین","روز مادر","روز پدر","مهمانی","هدیه","کادو"]);
 if(key==="time")return has(n,["روز","صبح","ظهر","شب","شبانه","هر دو","فرقی ندارد"]);
 if(key==="season")return has(n,["بهار","تابستان","پاییز","زمستان","همه فصل","فرقی ندارد"]);
 if(key==="longevity")return n.includes("ماندگاری")||has(n,["خیلی زیاد","خیلی بالا","بسیار زیاد","زیاد","بالا","متوسط","کم","ضعیف"]);
 if(key==="sillage")return n.includes("پخش بو")||n.includes("خط بو")||has(n,["خیلی قوی","پخش بالا","بمب","قوی","زیاد","بالا","متوسط","ملایم","کم","ضعیف"]);
 if(key==="scent")return scentMap.some(([,words])=>has(n,words));
 if(key==="birth_month")return months.some(m=>n.includes(m))||has(n,["ماه تولد","متولد"]);
 if(key==="budget")return has(n,["فرقی ندارد","مهم نیست","ندارم","بدون محدودیت","بودجه"])||/\d{4,}/.test(n);
 return false;
};

export const runtime="edge";
export async function POST(request:Request){try{
 const b=await request.json();const message=String(b.message||"").trim();if(!message)return NextResponse.json({error:"پیام خالی است."},{status:400});
 const prefs:Prefs=(b.preferences&&typeof b.preferences==="object"?b.preferences:{}) as Prefs;const it=intent(message);const current=nextKey(prefs);
 if(it==="address"||it==="social"||it==="support"){const x=await info(db());let reply="";if(it==="address")reply=x.address?"آدرس عطر کهکشان: "+x.address:"آدرس هنوز ثبت نشده است.";if(it==="support")reply=x.support_phone?"شماره پشتیبانی: "+x.support_phone:"شماره پشتیبانی هنوز ثبت نشده است.";if(it==="social")reply=Array.isArray(x.social_links)&&x.social_links.length?x.social_links.map((z:any)=>z?.name&&z?.url?z.name+": "+z.url:"").filter(Boolean).join("\n"):"پیج‌ها هنوز ثبت نشده‌اند.";return NextResponse.json({order_id:String(b.order_id||""),reply,done:false,intent:it,preferences:prefs})}
if(it==="catalog"){const {data}=await db().from("products").select("name,price,stock,full_size_ml,price_per_ml,per_ml_discount_percent,discount_percent,discount_start,discount_end").order("created_at",{ascending:false}).limit(12);const rows=(data||[]).filter((x:any)=>Number(x.stock)>0);const reply=rows.length?"محصولات موجود فعلی:\n"+rows.map((x:any)=>{const ml=Number(x.price_per_ml)||Number(x.price)/Math.max(1,Number(x.full_size_ml)||100);return "• "+x.name+" | بطری کامل "+money(Number(x.price))+" | هر میل "+money(ml)+" | موجودی: "+new Intl.NumberFormat("fa-IR").format(x.stock)}).join("\n"):"در حال حاضر محصول موجودی ثبت نشده است.";return NextResponse.json({order_id:String(b.order_id||""),reply,done:false,intent:it,preferences:prefs})}
 const extracted=extract(message,prefs,current||undefined);
 if(it==="greeting"&&!Object.keys(prefs).length)return NextResponse.json({order_id:String(b.order_id||""),reply:"به عطر کهکشان خوش آمدید ✦\nمن سلیقه شما را دقیق تحلیل می‌کنم. اول بگویید عطر می‌خواهید یا ادکلن؟",done:false,intent:"greeting",preferences:prefs});
 if(current&&it!=="greeting"&&!questionAccepts(current,message)){return NextResponse.json({order_id:String(b.order_id||""),reply:"این پاسخ مربوط به سؤال فعلی نیست. لطفاً فقط پاسخ همین سؤال را بگویید:\n\n"+questions[current],done:false,intent:"invalid",preferences:prefs})}
 for(const x of extracted){if(x.key==="scent")prefs.scent=x.value;else prefs[x.key]=x.value}
 const next=nextKey(prefs);
 if(next)return NextResponse.json({order_id:String(b.order_id||""),reply:questions[next],done:false,intent:it,preferences:prefs});
 const s=db();const {data:products}=await s.from("products").select("id,name,description,price,stock,image_url,fragrance_profile").gt("stock",0).limit(100);
 const picks=recommend(products||[],prefs);const pickText=picks.length?picks.map((x:any,i:number)=>(i+1)+". "+x.name+" | "+money(x.price)+" | تناسب تقریبی "+Math.min(99,70+x.score)+"٪").join("\n"):"در حال حاضر محصول کاملاً منطبق و موجود پیدا نشد.";
 const insert=await s.from("special_orders").insert({visitor_id:String(b.visitor_id||"").slice(0,80),first_name:String(prefs.first_name||""),last_name:String(prefs.last_name||""),phone:String(prefs.phone||""),preferences:prefs,status:"pending",notes:"پروفایل تشخیص عطر تکمیل شد."}).select("id").single();if(insert.error)throw insert.error;
 const reply="پروفایل رایحه شما کامل شد. ✦\n\nانتخاب‌های پیشنهادی:\n"+pickText+"\n\nدلیل انتخاب: "+[prefs.product_type,prefs.gender,(prefs.scent||[]).join("، "),prefs.season,prefs.occasion].filter(Boolean).join("، ");
 await s.from("special_order_messages").insert([{special_order_id:insert.data.id,role:"user",content:message},{special_order_id:insert.data.id,role:"assistant",content:reply}]);
 return NextResponse.json({order_id:insert.data.id,reply,done:true,intent:"recommendation",preferences:prefs,recommendations:picks.map((x:any)=>({id:x.id,name:x.name,price:x.price,image_url:x.image_url,score:x.score}))})
}catch{return NextResponse.json({error:"در پردازش پیام مشکلی پیش آمد. لطفاً دوباره تلاش کنید."},{status:500})}}