"use client";
import {useEffect,useState} from "react";
import {createSupabaseBrowserClient} from "@/lib/supabase-browser";
export default function LiveAdminStats(){
 const[path,setPath]=useState("");const[count,setCount]=useState(0);
 useEffect(()=>{setPath(location.pathname)},[]);
 useEffect(()=>{if(path!=="/admin")return;const supabase=createSupabaseBrowserClient();const channel=supabase.channel("galaxy-site-presence");const sync=()=>{const state=channel.presenceState();setCount(Object.keys(state).length)};channel.on("presence",{event:"sync"},sync).subscribe();return()=>{supabase.removeChannel(channel)}},[path]);
 if(path!=="/admin")return null;
 return <><section className="live-admin-stats"><div><span>LIVE</span><b>{new Intl.NumberFormat("fa-IR").format(count)}</b><small>بازدیدکننده آنلاین</small></div><div><span>STATUS</span><b>●</b><small>اتصال زنده فعال است</small></div></section><style jsx global>{` .live-admin-stats{position:fixed;left:18px;bottom:18px;z-index:80;display:flex;gap:10px;align-items:stretch;padding:10px;border:1px solid #473653;border-radius:16px;background:#100c18eF;box-shadow:0 16px 55px #0008;backdrop-filter:blur(12px)}.live-admin-stats>div{min-width:115px;padding:8px 12px;border:1px solid #30253a;border-radius:11px}.live-admin-stats span{display:block;color:#d9b75e;font-size:9px;letter-spacing:2px}.live-admin-stats b{display:block;color:#fff;font-size:22px;line-height:1.2}.live-admin-stats small{color:#93899d;font-size:10px}.stock-line{margin:0 17px;color:#a79daa;font-size:11px}.sold-out{opacity:.62}.sold-out .photo:before{content:"ناموجود";position:absolute;inset:0;z-index:5;display:grid;place-items:center;background:#08070db8;color:#fff;font-weight:700}.cart{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:13px 0;border-bottom:1px solid #29222f}.cart small{display:block;color:#8d8495;font-size:10px;margin-top:4px}.cart-controls{display:flex;align-items:center;gap:7px}.cart-controls button{min-width:31px;height:31px;border:1px solid #433650;background:#17121f;color:#fff;border-radius:8px}.cart-controls button:disabled{opacity:.4}.cart-controls .cart-remove{width:auto;padding:0 9px;color:#e1a0a0}.hero-address{color:#ff294f!important;text-shadow:0 0 8px #ff164455,0 0 22px #ff164433}.special-chat{position:relative}.new-chat{border:1px solid #4d3b5c;background:#17121f;color:#d9b75e;border-radius:9px;padding:7px 10px;cursor:pointer}.chat-head{flex-direction:row!important;justify-content:space-between;align-items:center}.chat-head>div{display:flex;flex-direction:column;gap:5px}footer{padding:28px 16px;text-align:center;color:#8f8796;border-top:1px solid #2b2332;font-size:11px;line-height:2.1}footer a{color:#d9b75e}@media(max-width:560px){.live-admin-stats{left:8px;bottom:8px;right:8px;justify-content:center}.live-admin-stats>div{min-width:0;flex:1;text-align:center}.cart-controls{gap:4px}.cart-controls button{min-width:29px}.new-chat{font-size:10px}.live-admin-stats b{font-size:18px}}`}</style></>
}