"use client";
import{useEffect,useState}from"react";
type Message={role:"user"|"assistant";content:string};
type Prefs=Record<string,unknown>;
const vid=()=>{let x=localStorage.getItem("galaxy_visitor_id");if(!x){x=crypto.randomUUID();localStorage.setItem("galaxy_visitor_id",x)}return x};
export default function SpecialPerfume(){
 const[messages,setMessages]=useState<Message[]>([]),[text,setText]=useState(""),[orderId,setOrderId]=useState(""),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[needsSpecial,setNeedsSpecial]=useState(false),[showForm,setShowForm]=useState(false),[preferences,setPreferences]=useState<Prefs>({}),[form,setForm]=useState({first_name:"",last_name:"",phone:""});
 useEffect(()=>{try{const saved=localStorage.getItem("galaxy_bot_order_id"),m=localStorage.getItem("galaxy_bot_messages"),p=localStorage.getItem("galaxy_bot_preferences");if(saved)setOrderId(saved);if(m)setMessages(JSON.parse(m));if(p)setPreferences(JSON.parse(p))}catch{}},[]);
 useEffect(()=>{if(orderId)localStorage.setItem("galaxy_bot_order_id",orderId);localStorage.setItem("galaxy_bot_messages",JSON.stringify(messages));localStorage.setItem("galaxy_bot_preferences",JSON.stringify(preferences))},[orderId,messages,preferences]);
 async function send(value=text.trim(),specialAction="",formData=form){if(!value||busy)return;setText("");setMessages(x=>[...x,{role:"user",content:value}]);setBusy(true);try{const r=await fetch("/api/special-order/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({order_id:orderId,message:value,visitor_id:vid(),preferences,special_action:specialAction,...(specialAction?formData:{})})});const d=await r.json();if(!r.ok)throw new Error(d?.error);setOrderId(d.order_id||orderId);setPreferences(d.preferences||preferences);setMessages(x=>[...x,{role:"assistant",content:d.reply||"پاسخی دریافت نشد."}]);setDone(Boolean(d.done));setNeedsSpecial(Boolean(d.needs_special_confirmation));if(d.needs_special_form)setShowForm(true);if(d.special_order_created){setShowForm(false);setNeedsSpecial(false)}}catch(e){setMessages(x=>[...x,{role:"assistant",content:e instanceof Error?e.message:"در پردازش پیام مشکلی پیش آمد."}])}finally{setBusy(false)}}
 function newChat(){localStorage.removeItem("galaxy_bot_order_id");localStorage.removeItem("galaxy_bot_messages");localStorage.removeItem("galaxy_bot_preferences");setOrderId("");setMessages([]);setPreferences({});setDone(false);setNeedsSpecial(false);setShowForm(false);setForm({first_name:"",last_name:"",phone:""});setText("")}
 return <section id="special" className="special-perfume"><div className="special-copy"><span>GALAXY SPECIAL</span><h2>مشاور هوشمند عطر کهکشان</h2><p>منظورتان را از متن فارسی تشخیص می‌دهم و فقط اطلاعاتی را که واقعاً لازم است می‌پرسم.</p><div className="special-points"><span>✦ تشخیص عطر یا ادکلن و جنسیت</span><span>✦ تحلیل روز، فصل، ماندگاری و پخش بو</span><span>✦ تطبیق با محصولات و قیمت واقعی فروشگاه</span><span>✦ سفارش ویژه با بررسی کارشناس</span></div></div><div className="special-chat"><div className="chat-head"><div><span>GALAXY BOT</span><b>موتور تشخیص نیت و رایحه</b></div><button className="new-chat" onClick={newChat}>＋ گفتگوی جدید</button></div><div className="chat-body">{messages.length===0&&<div className="bot-message">به عطر کهکشان خوش آمدید ✦<br/>اول بگویید: عطر می‌خواهید یا ادکلن؟</div>}{messages.map((m,i)=><div key={i} className={m.role==="user"?"user-message":"bot-message"}>{m.content}</div>)}{busy&&<div className="bot-message typing">در حال تحلیل پاسخ...</div>}{needsSpecial&&!showForm&&<button className="special-order-cta" onClick={()=>{setShowForm(true);send("بله، سفارش ویژه ثبت کن")}} disabled={busy}>ثبت سفارش عطر ویژه</button>}{showForm&&<div className="special-form"><b>ثبت سفارش ویژه</b><input value={form.first_name} onChange={e=>setForm({...form,first_name:e.target.value})} placeholder="نام"/><input value={form.last_name} onChange={e=>setForm({...form,last_name:e.target.value})} placeholder="نام خانوادگی"/><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="شماره تماس" inputMode="tel"/><button onClick={()=>send("اطلاعات اولیه سفارش ویژه را ثبت می‌کنم","create",form)} disabled={busy||!form.first_name.trim()||!form.last_name.trim()||!form.phone.trim()}>{busy?"در حال ثبت...":"ثبت سفارش ویژه"}</button></div>}</div><div className="chat-input"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")send()}} placeholder={done?"برای ادامه گفتگو پیام بدهید...":"پاسخ خود را بنویسید..."} disabled={busy}/><button onClick={()=>send()} disabled={busy||!text.trim()}>{busy?"تحلیل...":"ارسال"}</button></div></div></section>
}