"use client";

import Image from "next/image";
import {useEffect,useMemo,useState} from "react";
import {createSupabaseBrowserClient} from "@/lib/supabase-browser";
import SpecialPerfume from "@/app/components/special-perfume";

type P={id:string;name:string;description:string|null;price:number;stock:number;image_url:string|null;discount_percent:number;discount_start:string|null;discount_end:string|null;category_ids:string[];categories:any[]};
type Cat={id:string;name:string;slug:string;description:string|null};
type S={store_name:string;store_name_en:string;hero_title:string;hero_text:string;address:string|null;card_number:string|null;support_phone:string|null;social_links:any[]};
type C=P&{quantity:number};

const money=(n:number)=>new Intl.NumberFormat("fa-IR").format(Math.round(n))+" تومان";
const activeDiscount=(x:P)=>{const n=Date.now(),a=x.discount_start?new Date(x.discount_start).getTime():-Infinity,b=x.discount_end?new Date(x.discount_end).getTime():Infinity;return Number(x.discount_percent)>0&&n>=a&&n<=b};
const salePrice=(x:P)=>activeDiscount(x)?Number(x.price)*(1-Number(x.discount_percent)/100):Number(x.price);

function visitorId(){
  const key="galaxy_visitor_id";
  let id=localStorage.getItem(key);
  if(!id){id=crypto.randomUUID();localStorage.setItem(key,id)}
  return id;
}

export default function Home(){
  const[p,setP]=useState<P[]>([]),[cats,setCats]=useState<Cat[]>([]),[search,setSearch]=useState(""),[category,setCategory]=useState("all");
  const[s,setS]=useState<S>({store_name:"عطر کهکشان",store_name_en:"GALAXY",hero_title:"عطر کهکشان",hero_text:"رایحه‌ای که پیش از شما وارد اتاق می‌شود.",address:null,card_number:null,support_phone:null,social_links:[]});
  const[cart,setCart]=useState<C[]>([]),[bag,setBag]=useState(false),[checkout,setCheckout]=useState(false),[loading,setLoading]=useState(true);

  useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem("galaxy_cart")||"[]");if(Array.isArray(saved))setCart(saved)}catch{}},[]);
  useEffect(()=>{localStorage.setItem("galaxy_cart",JSON.stringify(cart))},[cart]);
  useEffect(()=>{let live=true;fetch("/api/storefront").then(r=>r.ok?r.json():Promise.reject()).then(d=>{if(!live)return;setP((d.products??[]) as P[]);setCats((d.categories??[]) as Cat[]);if(d.settings)setS({...d.settings,hero_title:"عطر کهکشان"} as S)}).catch(()=>{}).finally(()=>setLoading(false));return()=>{live=false}},[]);
  useEffect(()=>{const id=visitorId();const ping=()=>fetch("/api/analytics/heartbeat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({visitor_id:id,page:"storefront"})}).catch(()=>{});ping();const t=setInterval(ping,15000);return()=>clearInterval(t)},[]);

  const filtered=useMemo(()=>{const q=search.trim().toLocaleLowerCase("fa");return p.filter(x=>{const inCat=category==="all"||(x.category_ids||[]).includes(category);const text=((x.name||"")+" "+(x.description||"")+" "+(x.categories||[]).map((z:any)=>z.name).join(" ")).toLocaleLowerCase("fa");return inCat&&(!q||text.includes(q))})},[p,search,category]);
  const total=useMemo(()=>cart.reduce((a,x)=>a+salePrice(x)*x.quantity,0),[cart]);

  const add=(x:P)=>{if(x.stock<1)return;setCart(c=>{const q=c.find(i=>i.id===x.id);if(q)return c.map(i=>i.id===x.id?{...i,quantity:Math.min(x.stock,i.quantity+1)}:i);return[...c,{...x,quantity:1}]})};
  const changeQty=(id:string,delta:number)=>setCart(c=>c.map(i=>i.id===id?{...i,quantity:Math.max(0,Math.min(i.stock,i.quantity+delta))}:i).filter(i=>i.quantity>0));

  return <main>
    <header><a href="#home" className="brand"><span className="brand-bottle">♢</span>{s.store_name}<small>{s.store_name_en}</small></a><nav><a href="#products"><span>✦</span> عطرها</a><a href="#special"><span>◈</span> عطر ویژه</a><a href="#about"><span>◌</span> کهکشان</a><a href="#support"><span>♧</span> پشتیبانی</a></nav><div className="actions"><a href="/login"><span className="ui-icon">♙</span> ورود</a><button onClick={()=>setBag(true)}><span className="ui-icon">♧</span> سبد ({cart.reduce((n,x)=>n+x.quantity,0)})</button></div></header>
    <section id="home" className="hero"><div className="milky-galaxy" aria-hidden="true"><div className="galaxy-core"></div><div className="galaxy-dust"></div><svg className="galaxy-arms" viewBox="0 0 1200 700" preserveAspectRatio="none"><defs><filter id="galaxyGlow"><feGaussianBlur stdDeviation="7"/></filter></defs><path d="M600 350 C470 310 360 245 250 170 C145 99 65 130 18 205 C95 105 210 74 320 135 C430 196 515 255 600 350 C685 445 770 504 880 565 C990 626 1105 595 1182 495 C1135 570 1055 601 950 530 C840 455 730 390 600 350"/><path className="sharp" d="M600 350 C500 295 420 205 300 120 C185 38 80 75 20 165 C120 85 210 86 315 155 C425 229 515 310 600 350 C685 390 775 471 885 545 C990 614 1090 615 1180 535 C1120 625 1000 660 875 580 C760 506 690 415 600 350"/></svg>{Array.from({length:28},(_,i)=><i className="galaxy-star" key={i} style={{["--g" as string]:i}}><b>✦</b></i>)}</div><div className="hero-copy"><span>GALAXY PERFUMERY</span><h1>{s.hero_title}</h1>{s.address&&<div className="hero-address">⌖ {s.address}</div>}<p>{s.hero_text}</p><a className="gold" href="#products"><span>✦</span> کشف رایحه‌ها ↓</a></div></section>
    <section id="about" className="intro"><span>THE GALAXY</span><h2>رایحه، امضای شماست.</h2><p>انتخابی لوکس از عطرها و ادکلن‌ها برای لحظه‌هایی که باید ماندگار شوند.</p></section>
    <section id="products" className="catalog"><div className="section-head"><div><span>GALAXY PERFUME STORE</span><h2>فروشگاه عطر کهکشان</h2></div><b>{filtered.length} رایحه</b></div><div className="catalog-tools"><label className="search-box"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="جست‌وجوی نام عطر، رایحه یا دسته‌بندی..." aria-label="جست‌وجوی محصول"/></label><div className="category-tabs"><button className={category==="all"?"active":""} onClick={()=>setCategory("all")}>همه</button>{cats.map(x=><button key={x.id} className={category===x.id?"active":""} onClick={()=>setCategory(x.id)}>{x.name}</button>)}</div></div>
    {loading?<div className="empty">در حال بارگذاری رایحه‌ها...</div>:filtered.length?<div className="grid">{filtered.map(x=>{const sale=activeDiscount(x),final=salePrice(x),out=x.stock<1;return <article className={"card "+(out?"sold-out":"")} key={x.id}><div className="photo">{sale&&<span className="discount-badge">{new Intl.NumberFormat("fa-IR").format(Number(x.discount_percent))}٪ تخفیف</span>}{x.image_url?<Image src={x.image_url} alt={x.name} fill sizes="(max-width:560px) 50vw,(max-width:900px) 50vw,25vw" loading={p.indexOf(x)<2?"eager":"lazy"} priority={p.indexOf(x)<2}/>:<div className="bottle-mark"><span>✦</span><small>GALAXY</small></div>}</div><h3>{x.name}</h3><p>{x.description}</p><div className="stock-line">{out?"ناموجود":"موجودی: "+new Intl.NumberFormat("fa-IR").format(x.stock)+" عدد"}</div><div className="price-area">{sale&&<del>{money(Number(x.price))}</del>}<strong>{money(final)}</strong></div><div className="row"><button disabled={out} onClick={()=>add(x)}><span>♧</span>{out?"ناموجود":"افزودن به سبد"}</button></div></article>})}</div>:<div className="empty">{p.length?"محصولی با این جست‌وجو یا دسته‌بندی پیدا نشد.":"هنوز محصولی ثبت نشده است."}</div>}</section>
    <SpecialPerfume/>
    <section id="support" className="support"><div><span>NEED HELP?</span><h2>برای انتخاب رایحه کنار شما هستیم.</h2><p>برای انتخاب عطر یا پیگیری سفارش با پشتیبانی در ارتباط باشید.</p>{s.address&&<div className="support-address">⌖ {s.address}</div>}{Array.isArray(s.social_links)&&s.social_links.filter((x:any)=>x?.url).length>0&&<div className="social-links">{s.social_links.filter((x:any)=>x?.url).map((x:any)=><a key={x.name} href={x.url} target="_blank" rel="noreferrer">{x.name}</a>)}</div>}</div><a className="gold" href={s.support_phone?"tel:"+s.support_phone:"#"}><span>♧</span> پشتیبانی رایحه</a></section>
    <footer>تمام حقوق سایت مربوط به تیم همراه یار می باشد و شامل قوانین کپی رایت است. <span>ارتباط با تیم تخصصی همراه یار <a href="https://instagram.com/Hamrahyar" target="_blank" rel="noreferrer">@Hamrahyar</a> در اینستا</span></footer>
    {bag&&<div className="overlay"><aside className="drawer"><button className="x" onClick={()=>setBag(false)}>×</button><span>YOUR BAG</span><h2>سبد خرید</h2>{cart.length?cart.map(x=><div className="cart" key={x.id}><div><b>{x.name}</b><small>موجودی: {new Intl.NumberFormat("fa-IR").format(x.stock)}</small></div><div className="cart-controls"><button onClick={()=>changeQty(x.id,-1)}>−</button><b>{new Intl.NumberFormat("fa-IR").format(x.quantity)}</b><button disabled={x.quantity>=x.stock} onClick={()=>changeQty(x.id,1)}>+</button><button className="cart-remove" onClick={()=>setCart(c=>c.filter(i=>i.id!==x.id))}>حذف</button></div></div>):<div className="empty">سبد خالی است.</div>}<h3 className="total">جمع: {money(total)}</h3>{cart.length>0&&<button className="gold full" onClick={()=>{setBag(false);setCheckout(true)}}><span>♧</span> ادامه به پرداخت</button>}</aside></div>}
    {checkout&&<Checkout s={s} cart={cart} total={total} close={()=>setCheckout(false)} done={()=>{setCart([]);setCheckout(false)}}/>}
  </main>
}

function Checkout({s,cart,total,close,done}:{s:S;cart:C[];total:number;close:()=>void;done:()=>void}){
  const[f,setF]=useState<any>({customer_full_name:"",phone:"",province:"",city:"",address:"",postal_code:"",payer_full_name:"",payment_tracking_code:""}),[step,setStep]=useState(1),[msg,setMsg]=useState(""),[submitted,setSubmitted]=useState(false),[orderToken,setOrderToken]=useState(""),[orderStatus,setOrderStatus]=useState(""),[busy,setBusy]=useState(false);
  const set=(k:string,v:string)=>setF((x:any)=>({...x,[k]:v}));
  const send=async()=>{if(busy)return;setBusy(true);try{const r=await fetch("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...f,items:cart.map(x=>({product_id:x.id,quantity:x.quantity}))})});const d=await r.json();if(!r.ok){setMsg(d.error||"خطا در ثبت سفارش");return}setOrderToken(d.public_token||"");setSubmitted(true);setOrderStatus("pending");setMsg("سفارش ثبت شد. پس از تأیید پرداخت، ساخت حساب برای شما فعال می‌شود.")}finally{setBusy(false)}};
  return <div className="overlay"><div className="checkout"><button className="x" onClick={close}>×</button>{submitted?<AccountAfterPayment token={orderToken} status={orderStatus} setStatus={setOrderStatus} done={done}/>:<><span>STEP {step} / 2</span>{step===1?<><h2>اطلاعات ارسال</h2><div className="fields">{[["customer_full_name","نام و نام خانوادگی"],["phone","شماره تماس"],["province","استان"],["city","شهرستان"],["postal_code","کدپستی"]].map(([k,l])=><label key={k}>{l}<input value={f[k]} onChange={e=>set(k,e.target.value)}/></label>)}<label>آدرس دقیق<textarea value={f.address} onChange={e=>set("address",e.target.value)}/></label></div>{msg&&<p>{msg}</p>}<button className="gold full" onClick={()=>{if(!f.customer_full_name||!f.phone||!f.province||!f.city||!f.address||!f.postal_code){setMsg("همه فیلدهای ارسال اجباری هستند.");return}setMsg("");setStep(2)}}>ادامه به پرداخت</button></>:<><h2>کارت به کارت</h2><div className="payment"><small>مبلغ قابل پرداخت</small><strong>{money(total)}</strong><small>شماره کارت فروشگاه</small><code>{s.card_number||"هنوز ثبت نشده"}</code></div><label>نام و نام خانوادگی واریز کننده<input value={f.payer_full_name} onChange={e=>set("payer_full_name",e.target.value)}/></label><label>شناسه پرداخت<input value={f.payment_tracking_code} onChange={e=>set("payment_tracking_code",e.target.value)}/></label>{msg&&<p>{msg}</p>}<button className="gold full" disabled={busy} onClick={()=>{if(!f.payer_full_name||!f.payment_tracking_code){setMsg("نام و شناسه پرداخت اجباری است.");return}send()}}>{busy?"در حال ثبت سفارش...":"ثبت نهایی سفارش"}</button></>}</>}</div></div>
}

function AccountAfterPayment({token,status,setStatus,done}:{token:string;status:string;setStatus:(x:string)=>void;done:()=>void}){
  const supabase=createSupabaseBrowserClient();const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
  useEffect(()=>{if(!token)return;let stop=false;const check=async()=>{const r=await fetch("/api/orders/status?token="+encodeURIComponent(token));if(!r.ok)return;const d=await r.json();if(!stop)setStatus(d.status)};check();const t=setInterval(check,6000);return()=>{stop=true;clearInterval(t)}},[token,setStatus]);
  async function create(){if(busy)return;if(password.length<8){setMsg("رمز عبور باید حداقل ۸ کاراکتر باشد.");return}if(password!==confirm){setMsg("تکرار رمز عبور با رمز اصلی یکسان نیست.");return}setBusy(true);setMsg("");const{data,error}=await supabase.auth.signUp({email:email.trim(),password,options:{data:{full_name:""}}});if(error){setMsg(error.message.includes("already")?"این ایمیل قبلاً ثبت شده است. از بخش ورود وارد شوید.":"ساخت حساب انجام نشد.");setBusy(false);return}if(data.session){await fetch("/api/orders/attach",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+data.session.access_token},body:JSON.stringify({token})});setMsg("حساب شما ساخته شد و سفارش به حساب متصل شد.");setTimeout(()=>{done();location.href="/account"},900)}else{localStorage.setItem("galaxy_pending_order_token",token);setMsg("حساب ایجاد شد. ایمیل خود را تأیید کنید و سپس وارد حساب شوید.");setBusy(false)}}
  if(status!=="paid")return <div className="account-wait"><span>PAYMENT CONFIRMATION</span><h2>در انتظار تأیید پرداخت</h2><p>سفارش شما ثبت شده است. به محض تأیید پرداخت توسط عطر کهکشان، فرم ساخت حساب نمایش داده می‌شود.</p><div className="status-pulse">● در حال بررسی وضعیت سفارش</div></div>;
  return <div className="account-create"><span>GALAXY MEMBER</span><h2>حساب خود را بسازید</h2><p>پرداخت تأیید شد. با ساخت حساب، سفارش شما به حساب دائمی‌تان متصل می‌شود.</p><label>ایمیل<input type="email" dir="ltr" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>رمز عبور<input type="password" dir="ltr" value={password} onChange={e=>setPassword(e.target.value)}/></label><label>تکرار رمز عبور<input type="password" dir="ltr" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label>{msg&&<p>{msg}</p>}<button className="gold full" disabled={busy||!email||!password||!confirm} onClick={create}>{busy?"در حال ساخت حساب...":"ساخت حساب کاربری"}</button></div>
}
